### ISSUE TITLE
Run MultiplyMatrixByConstant.scala with scalap

### ISSUE THREAD

**Issue by ghost** [phatak-dev/introduction_to_ml_with_spark#1]
I had used scala with gradle build system in other projects. 
But in this ml repo, i am not seeing any sbt file.

So, i tried to compile one of the files and run it as,

`scalac MultiplyMatrixByConstant.scala`
It gives error as,

```
MultiplyMatrixByConstant.scala:3: error: not found: object breeze
import breeze.linalg.{DenseMatrix, DenseVector}
       ^
one error found
```

How can i try out at least one example to confirm my scala bins and libs are properly set up for the workshop?

**Comment by phatak-dev** [comment]
Hi,
It's a maven project. Use maven clean install  to build and provided steps
to run the examples.

**Comment by ghost** [comment]
thanks phatak. It works.

`java -cp target/spark-ml-examples.jar com.madhukaraphatak.spark.breeze.MultiplyVectorByConstant`
command works as well, after i removed the last argument `local`.
